batch_size: 32
seq_len: 96
predict_len: 96
do_eval: True
epoch: 5

dataset: 
  name: TSDataset
  dataset_root: /data/
  train_path: /data/train.csv
  val_path: /data/val.csv
  time_feat: False
  scale: True


info_params:
  freq: 1h
  target_cols: "OT"
  time_col: date


model: 
  name: PatchTSTModel
  model_cfg:
    c_in: 1
    n_layers: 3
    n_heads: 16
    d_model: 128
    d_ff: 256
    dropout: 0.2
    fc_dropout: 0.2
    head_dropout: 0.0
    patch_len: 16
    stride: 8
    patience: 10
    optimizer_params:
      learning_rate: 0.0001
      gamma: 0.9
