Global:
  model: PP-LCNet_x1_0_doc_ori
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/cls/cls_flowers_examples"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  convert:
    enable: False
    src_dataset_type: null
  split:
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 4
  epochs_iters: 50
  batch_size: 16
  learning_rate: 0.08
  pretrain_weight_path: null
  warmup_steps: 100
  resume_path: null
  log_interval: 10
  eval_interval: 1
  save_interval: 1

Evaluate:
  weight_path: "output/best_model.pdparams"
  log_interval: 10

Export:
  weight_path: https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/PPLCNet_x1_0_docori_pretrained.pdparams

Predict:
  model_dir: "output/best_model"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/img_rot180_demo.jpg"
  kernel_option:
    run_mode: paddle
    batch_size: 1
