batch_size: 1
iters: 20
output_op: none

model:
  type: STFPM
  backbone:
    type: ResNet18

train_dataset:
  type: Dataset
  num_classes: 1
  dataset_root: /mv_dataset/hazelnut
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: train

val_dataset:
  type: Dataset 
  num_classes: 1
  dataset_root: /mv_dataset/hazelnut
  transforms:
    - type: Resize
      target_size: [256, 256]
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  mode: val

loss:
  types:
    - type: DistillationLoss
  coef: [1]

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.4
  end_lr: 0.4
  power: 0.9

