Global:
  model: SLANet
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/table_rec/table_rec_dataset_examples"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  convert:
    enable: False
    src_dataset_type: null
  split:
    enable: False
    train_percent: null
    val_percent: null

Train:
  epochs_iters: 10
  batch_size: 48
  learning_rate: 0.001
  pretrain_weight_path: null
  resume_path: null
  log_interval: 20
  eval_interval: 1
  save_interval: 1

Evaluate:
  weight_path: "output/best_accuracy/best_accuracy.pdparams"
  log_interval: 1

Export:
  weight_path: https://paddleocr.bj.bcebos.com/pretrained/ch_PP-StructrureV2_SLANet_trained.pdparams

Predict:
  model_dir: "output/best_accuracy/inference"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/table_recognition.jpg"
  batch_size: 1
  kernel_option:
    run_mode: paddle
