Global:
  model: PP-ShiTuV2_rec_CLIP_vit_base
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/shitu_rec/Inshop_examples"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    gallery_percent: null
    query_percent: null

Train:
  num_classes: 159
  epochs_iters: 20
  batch_size: 32
  learning_rate: 0.001
  pretrain_weight_path: https://paddleclas.bj.bcebos.com/models/PP-ShiTu/PP-ShiTuV2_rec_CLIP_vit_base_pretrained.pdparams
  warmup_steps: 5
  resume_path: null
  log_interval: 1
  eval_interval: 1
  save_interval: 1

Evaluate:
  weight_path: "output/best_model/best_model.pdparams"
  log_interval: 1

Export:
  weight_path: https://paddleclas.bj.bcebos.com/models/PP-ShiTu/PP-ShiTuV2_rec_CLIP_vit_base_pretrained.pdparams

Predict:
  batch_size: 1
  model_dir: "output/best_model/inference"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_recognition_001.jpg"
  kernel_option:
    run_mode: paddle
