Global:
  model: NLinear
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/ts_fc/ts_dataset_examples"
  device: gpu:0
  output: "output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  time_col: date
  target_cols: OT
  freq: 1h
  input_len: 96
  predict_len: 96
  epochs_iters: 40
  batch_size: 16
  learning_rate: 0.0001
  patience: 10

Evaluate:
  weight_path: "output/best_model/model.pdparams"

Export:
  weight_path: https://paddlets.bj.bcebos.com/dygraph/NLinear.pdparams.tar

Predict:
  batch_size: 1
  model_dir: "output/inference"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/ts/demo_ts/ts_fc.csv"
