Global:
  model: PatchTST_ad
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/ts_ad/ts_anomaly_examples/"
  device: gpu:0
  output: "output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  time_col: timestamp
  feature_cols: feature_0,feature_1
  label_col: label
  freq: 1
  input_len: 96
  epochs_iters: 20
  batch_size: 16
  learning_rate: 0.0005

Evaluate:
  weight_path: "output/best_accuracy.pdparams.tar"

Export:
  weight_path: https://paddlets.bj.bcebos.com/dygraph/PatchTST_ad.pdparams.tar

Predict:
  model_dir: "output/inference"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/ts/demo_ts/ts_ad.csv"
