Global:
  model: TimesNet_cls
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/ts_cls/ts_classify_examples"
  device: gpu:0
  output: "output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  time_col: time
  target_cols: dim_0,dim_1,dim_2
  group_id: group_id
  static_cov_cols: label
  freq: 1
  epochs_iters: 40
  batch_size: 16
  learning_rate: 0.0001

Evaluate:
  weight_path: "output/best_accuracy.pdparams.tar"

Export:
  weight_path: https://paddlets.bj.bcebos.com/dygraph/TimesNet_cls.pdparams.tar

Predict:
  model_dir: "output/inference"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/ts/demo_ts/ts_cls.csv"
