Global:
  model: PP-OCRv4_mobile_seal_det
  mode: check_dataset # check_dataset/train/evaluate/predict
  module: text_det
  dataset_dir: "/paddle/dataset/paddlex/ocr_det/ocr_curve_det_dataset_examples"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  convert:
    enable: False
    src_dataset_type: null
  split:
    enable: False
    train_percent: null
    val_percent: null

Train:
  epochs_iters: 100
  batch_size: 8
  learning_rate: 0.001
  pretrain_weight_path: null
  resume_path: null
  log_interval: 10
  eval_interval: 1
  save_interval: 1

Evaluate:
  weight_path: "output/best_accuracy/best_accuracy.pdparams"
  log_interval: 1

Export:
  weight_path: https://paddleocr.bj.bcebos.com/pretrained/ch_PP-OCRv4_mobile_det_curve_trained.pdparams

Predict:
  batch_size: 1
  model_dir: "output/best_accuracy/inference"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/seal_text_det.png"
  kernel_option:
    run_mode: paddle
