Global:
  model: RT-DETR-R18
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/det/det_coco_examples"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  convert:
    enable: False
    src_dataset_type: nul
  split:
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 4
  epochs_iters: 40
  batch_size: 16
  learning_rate: 0.0002
  pretrain_weight_path: null
  warmup_steps: 100
  resume_path: null
  log_interval: 10
  eval_interval: 1

Evaluate:
  weight_path: "output/best_model.pdparams"
  log_interval: 10

Predict:
  model_dir: "output/best_model"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_object_detection_002.png"
  kernel_option:
    run_mode: paddle
    batch_size: 1