Global:
  model: LZ-MobileNetV3_large_x1_0
  mode: check_dataset # check_dataset/train/evaluate/predict
  dataset_dir: "/paddle/dataset/paddlex/cls/cls_flowers_examples"
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: True
    train_percent: 70
    val_percent: 30

Train:
  num_classes: 102
  epochs_iters: 20
  batch_size: 8
  learning_rate: 0.01
  pretrain_weight_path: "https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/legendary_models/MobileNetV3_large_x1_0_pretrained.pdparams"
  warmup_steps: 5
  resume_path: null
  log_interval: 1
  eval_interval: 1
  save_interval: 1

Evaluate:
  weight_path: "output/best_model.pdparams"
  log_interval: 1

Export:
  weight_path: "output/best_model.pdparams"

Predict:
  model_dir: "output/best_model"
  input_path: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_classification_001.jpg"
  kernel_option:
    run_mode: paddle
    batch_size: 1
