Global:
  model: PP-LCNet_x1_0_ML
  mode: check_dataset # check_dataset/train/evaluate/predict/predict
  dataset_dir: dataset/mlcls_nus_examples
  device: gpu:0,1,2,3
  output: "output"

CheckDataset:
  convert: 
    enable: False
    src_dataset_type: null
  split: 
    enable: False
    train_percent: null
    val_percent: null

Train:
  num_classes: 33
  epochs_iters: 20
  batch_size: 32
  learning_rate: 0.1
  pretrain_weight_path: null
  warmup_steps: 5
  resume_path: null
  log_interval: 20
  eval_interval: 1
  save_interval: 1

Evaluate:
  weight_path: "output/best_model/best_model.pdparams"
  log_interval: 1

Export:
  weight_path: https://paddleclas.bj.bcebos.com/models/multi_label/PP-LCNet_x1_0_ml_decoder_448_pretrained.pdparams

Predict:
  batch_size: 1
  model_dir: "output/best_model/inference"
  input: "https://paddle-model-ecology.bj.bcebos.com/paddlex/imgs/demo_image/general_image_classification_001.jpg"
  kernel_option:
    run_mode: paddle
